COLOR_WHITE = (255,255,255)
COLOR_YELLOW = (225,225,0)

MENU_OPTION = ('NOVO JOGO 1P',
               'NOVO JOGO 2P - COPERATIVO',
               'NOVO JOGO 2P - COMPETITIVO',
               'RECORDE',
               'SAIR')


WIN_WIDTH = 640
WIN_HEIGHT = 360
